# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
#  config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.10.14"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.10.15"
  end

  # install docker and pull ubuntu image  
  config.vm.provision "docker" do |d|
    d.pull_images "ubuntu"
  end

  # install weave
  config.vm.provision "shell", inline: <<-SHELL
    sudo curl -L git.io/weave -o /usr/local/bin/weave
    sudo chmod +x /usr/local/bin/weave
    weave launch
  SHELL
end
